### ISSUE TITLE
'OSError: Please check path of your src vocab file!' Despite valid path

### ISSUE THREAD

**Issue by atticusha** [OpenNMT/OpenNMT-py#1913]
Hi,

I've previously been able to run onmt, but recently when I made some adjustments to my training data, I started getting `OSError: Please check path of your src vocab file!` errors when running `onmt_build_vocab`, despite the src vocab path being valid.

I decided to download the toy-ende example and am having the same issue. My yaml file looks like this:

```
# toy_en_de.yaml

# ## Where the samples will be written
save_data: /scratch/a/b/train-crk/toy-ende/run/
## Where the vocab(s) will be written
src_vocab: /scratch/a/b/train-crk/toy-ende/run/example.vocab.src
tgt_vocab: /scratch/a/b/train-crk/toy-ende/run/example.vocab.tgt
# # Prevent overwriting existing files in the folder
overwrite: False

# # Corpus opts:
data:
    corpus_1:
        path_src: /scratch/a/b/train-crk/toy-ende/src-train.txt
        path_tgt: /scratch/a/b/train-crk/toy-ende/tgt-train.txt
    valid:
        path_src: /scratch/a/b/train-crk/toy-ende/src-val.txt
        path_tgt: /scratch/a/b/train-crk/toy-ende/tgt-val.txt
```

The contents of toy-ende/ is populated with the following times:

`run/
src-train.txt
tgt-test.txt
tgt-val.txt
src-test.txt
src-val.txt
tgt-train.txt
toy_en_de.yaml`

The `run/` directory is a valid but empty directory. I have full permissions in all folders. 

Am I missing something? After running into these issues, I've pulled the most recent verbs and still have the issue. I don't recall having this issue previously. 

Thank you.
