### ISSUE TITLE
onmt_train: error: unrecognized arguments while applying tokenization on the fly.

### ISSUE THREAD

**Issue by ishaansharma** [OpenNMT/OpenNMT-py#1976]
Respected Fellow Researchers, 
I was going through the FAQ on github and came across one of the Question, which I tried . 
That is , How can I apply tokenization and subword regularization when training.  Please find the link below:

[Github FAQ Link](https://github.com/OpenNMT/OpenNMT-py/blob/7a93327bcc6465a631c91fbd0356420a0fc33c05/docs/source/FAQ.md#how-can-i-apply-on-the-fly-tokenization-and-subword-regularization-when-training)

I tried running this with onmt_train and got error listed below:

`onmt_train: error: unrecognized arguments: --src_subword_type=bpe --src_subword_model=8G4inSTout-spire/bpe.model --tgt_subword_type=bpe --tgt_subword_model=8G4inSTout-spire/bpe.model --subword_nbest=20 --subword_alpha=0.1 --src_onmttok_kwargs={'mode':'none', 'spacer_annotate': True} --tgt_onmttok_kwargs={'mode': 'none', 'spacer_annotate': True}`

My YML file is like this : 
```
save_model: 'output/model/newmodel'
save_checkpoint_steps: 10000
keep_checkpoint: 2
seed: 3000
train_steps: 500000
valid_steps: 5000
warmup_steps: 8000
report_every: 100

# Tokenization options
src_subword_type: bpe
src_subword_model: /bpe.model
tgt_subword_type: bpe
tgt_subword_model: /bpe.model

# Specific arguments for pyonmttok
src_onmttok_kwargs: "{'mode': 'none', 'spacer_annotate': True}"
tgt_onmttok_kwargs: "{'mode': 'none', 'spacer_annotate': True}"

# Corpus opts:
data: 
    corpus_1:
        path_src: 8G4inSTout-spire/100_train_src.txt
        path_tgt: 8G4inSTout-spire/100_train_tgt.txt
        transforms: [onmt_tokenize]
        weight: 1
    valid:
        path_src: 8G4inSTout-spire/50_val_src.txt
        path_tgt: 8G4inSTout-spire/50_val_tgt.txt
        transforms: [onmt_tokenize]


decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6 
transformer_ff: 2048
heads: 8

global_attention: general #mlp

generator_function: softmax

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.2
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

early_stopping: 5

world_size: 1
gpu_ranks: 0
gpu_verbose_level: 1
```

Is it possible to perform this task with current version . If yes please suggest how I can achieve this task.
