### ISSUE TITLE
<unk> appearing in 2.0.x despite using Sentencepiece/BPE

### ISSUE THREAD

**Issue by JOHW85** [OpenNMT/OpenNMT-py#2020]
I've trained two non-vanilla (big and deep) Transformers with v2 using both Sentencepiece and YouTokenToMe's BPE. I've noticed that there are plenty of <unk>s generated prior to detokenizing via Sentencepiece. Those terms frequently appear in my corpus as well (like a name), so it's quite unlikely that the corpus hasn't seen it. Besides, I do have a mapping for one of the particular terms in my Sentencepiece .vocab file.

In 1.2.0, this didn't happen (it was a big Transformer) back then, so other than some architectural differences in the model, the corpus used is slightly bigger than the older version. So I can only guess that something happened in the move to v2.

Training is done past 500k steps for over 22million lines.

Example of yaml file. I'm not sure if it has to do with the vocabulary files that are created prior to the training.
```
## Where the vocab(s) will be written
save_data: v3_big
# Vocabulary files that were just created
src_vocab: v3_big.vocab.src
tgt_vocab: v3_big.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: True
# Corpus opts:
data:
    corpus_1:
        path_src: v3_big.cleaned.zh
        path_tgt: v3_big.cleaned.en
        path_align:v3_big.cleaned.tok.align
        transforms: [filtertoolong]
        weight: 1
    valid:
        path_src: v3_big_val.tok.zh
        path_tgt: v3_big_val.tok.en
        path_align:v3_big_val.tok.align
        transforms: [filtertoolong]
# Preprocessing Settings
src_seq_length: 250
tgt_seq_length: 250

# General opts
save_model: v3_deep
save_checkpoint_steps: 10000
valid_steps: 10000
train_steps: 4000000

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 1
gpu_ranks: [0]
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 16000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 12
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.3]
attention_dropout: [0.1]

# Tensorboard
tensorboard: true
tensorboard_log_dir: logs/
```
