### ISSUE TITLE
ValueError: specified tranform not supported!

### ISSUE THREAD

**Issue by zoe9823** [OpenNMT/OpenNMT-py#2147]
Thanks for adding src feats! But when I try `onmt_build_vocab -config features_data.yaml -n_sample 10000`
happends:

File "/home/zoe/OpenNMT-py/onmt/transforms/__init__.py", line 18, in get_transforms_cls
    raise ValueError("specified tranform not supported!")
ValueError: specified tranform not supported!

how to fix it?

### features_data.yaml

```
## Where the samples will be written
save_data: data/data_features/factors/
## Where the vocab(s) will be written
src_vocab: data/data_features/factors/vocab.src
tgt_vocab: data/data_features/factors/vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False
# Corpus opts:
data:
    corpus_1:
        path_src: data/data_features/factors/src-train.txt
        path_tgt: data/data_features/factors/tgt-train.txt
        src_feats:
            feat0: data/data_features/factors/src-train.feat0
        transforms: [filterfeats, inferfeats]
    valid:
        path_src: data/data_features/factors/src-val.txt
        path_tgt: data/data_features/factors/tgt-val.txt
        src_feats:
            feat0: data/data_features/factors/src-val.feat0

```
@anderleich
