### ISSUE TITLE
Problem of batchsize and GPU memory

### ISSUE THREAD

**Issue by medicine-wave** [OpenNMT/OpenNMT-py#2316]
When I change the  batch_size from 128 to 64, My GPU memory doesn't seem to have been halved, it's still full. Is there any mechanism for this?

```
data:
  corpus_1:
    path_src: src_train.txt
    path_tgt: tgt_train.txt
  valid:
    path_src: src_val.txt
    path_tgt: tgt_val.txt

n_sample: 0
save_data: vocab
src_vocab: vocab/vocab.src
tgt_vocab: vocab/vocab.src
share_vocab: 'true'
src_seq_length: 500
tgt_seq_length: 500
overwrite: 'true'

save_model: model.product_reactants
save_checkpoint_steps: 50000
keep_checkpoint: 40
seed: 42
train_steps: 2000000
valid_steps: 50000
warmup_steps: 8000
report_every: 1000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
hidden_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 128
valid_batch_size: 128
batch_type: sents
normalization: sents
dropout: 0.3
attention_dropout: 0.3
label_smoothing: 0.0

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks: [0]
```
