### ISSUE TITLE
Some questions about fine-tune nllb-200

### ISSUE THREAD

**Issue by ILG2021** [OpenNMT/OpenNMT-py#2457]
Hello, thanks for your wonderful job. It makes us every easy to use nllb-200. I have see the tutorial about fine-tune nllb-200, very easy. But still I have some questions:
1. If I have trained english-chinese, should I train chinese-english also?
2. how to train multi-language? use array in the data section? like this?
```
   data:
        -custom-tlzh:
            path_src: "./nllb-200/dataset.tl"
            path_tgt: "./nllb-200/dataset.zh"
            transforms: [sentencepiece, prefix, suffix, filtertoolong]
            weight: 10
            src_prefix: "</s> tgl_Latn"
            tgt_prefix: "zho_Hans"
            src_suffix: ""
            tgt_suffix: ""
        -custom-enzh:
            path_src: "./nllb-200/dataset.en"
            path_tgt: "./nllb-200/dataset.zh"
            transforms: [sentencepiece, prefix, suffix, filtertoolong]
            weight: 10
            src_prefix: "</s> eng_Latn"
            tgt_prefix: "zho_Hans"
            src_suffix: ""
            tgt_suffix: ""
```
