### ISSUE TITLE
Can not finetune nllb-200-3.3B

### ISSUE THREAD

**Issue by ILG2021** [OpenNMT/OpenNMT-py#2458]
I have successfully finetune nllb-200-1.3B by fellowing the tutorial here:
https://forum.opennmt.net/t/finetuning-and-curating-nllb-200-with-opennmt-py/5238
Everything is ok. But when I finetune 3.3B, it always stops at build modeling and gives nothing about the error.
I run the train.py on the colab and vast.ai, both are notebook.

**Comment by ILG2021** [comment]
This is my train config:
```
share_vocab: true
src_vocab: "./nllb-200/dictionary2.txt"
src_words_min_frequency: 1
src_vocab_size: 257284
tgt_vocab: "./nllb-200/dictionary2.txt"
tgt_words_min_frequency: 1
tgt_vocab_size: 257284
vocab_size_multiple: 1
decoder_start_token: '</s>'
#### Subword
src_subword_model: "./nllb-200/flores200_sacrebleu_tokenizer_spm2.model"
tgt_subword_model: "./nllb-200/flores200_sacrebleu_tokenizer_spm2.model"
src_subword_nbest: 1
src_subword_alpha: 0.0
tgt_subword_nbest: 1
tgt_subword_alpha: 0.0
# Corpus opts:
data:
    custom-tl-zh:
        path_src: "./nllb-200/dataset.tl"
        path_tgt: "./nllb-200/dataset.zh"
        transforms: [sentencepiece, prefix, suffix, filtertoolong]
        weight: 10
        src_prefix: "tgl_Latn"
        tgt_prefix: "zho_Hans"
        src_suffix: "</s>"
        tgt_suffix: ""
update_vocab: true
train_from: "./nllb-200/nllb-200-3.3B-onmt.pt"
reset_optim: all
save_data: "nllb-200"
save_model: "./nllb-200/nllb-200-3.3B-onmt.pt"
log_file: "./nllb-200/nllb-200-3.3B-onmt.log"
keep_checkpoint: 100
save_checkpoint_steps: 4000
average_decay: 0.0005
seed: 1234
report_every: 10
train_steps: 4000
valid_steps: 100
# Batching
bucket_size: 262144
num_workers: 4
prefetch_factor: 400
world_size: 1
gpu_ranks: [0]
batch_type: "tokens"
batch_size: 512
valid_batch_size: 384
batch_size_multiple: 1
accum_count: [32, 32, 32]
accum_steps: [0, 15000, 30000]
# Optimization
model_dtype: "fp16"
optim: "sgd"
learning_rate: 30
warmup_steps: 100
decay_method: "noam"
adam_beta2: 0.98
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
override_opts: true
encoder_type: transformer
decoder_type: transformer
enc_layers: 24
dec_layers: 24
heads: 16
hidden_size: 2048
word_vec_size: 2048
transformer_ff: 8192
dropout_steps: [0, 15000, 30000]
dropout: [0.1, 0.1, 0.1]
attention_dropout: [0.1, 0.1, 0.1]
share_decoder_embeddings: true
share_embeddings: true
position_encoding: true
position_encoding_type: 'SinusoidalConcat'
```
